[book]
authors = ["Benjamin Cretois"]
language = "en"
multilingual = false
src = "src"
title = "Documentation on using HPC and containers for Machine Learning"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/NINAnor/91126800_ML_and_associated_tech"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
