[book]
authors = ["Benjamin Cretois"]
language = "en"
src = "src"
title = "Documentation on using HPC and containers for Machine Learning"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
git-repository-url = "https://github.com/NINAnor/91126800_ML_and_associated_tech"
mathjax-support = true
site-url = "/mdBook/"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
