[dependency-groups]
dev = [
  "deptry"
]

[project]
authors = [
  {name = "Francesco Frassinelli", email = "francesco.frassinelli@nina.no"}
]
dependencies = [
  "django-environ"
]
description = ""
license = "GPL-3.0+"
name = "ml_and_associated_tech"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"

[project.scripts]
ml_and_associated_tech = "main:start"

[tool.deptry]
extend_exclude = ["book", "src/case_study"]
known_first_party = []

[tool.ruff]
extend-exclude = ["book", "src/case_study"]
fix = true

[tool.ruff.lint]
ignore = ["COM812"]
select = ["E", "W", "I", "F", "UP", "S", "B", "A", "COM", "LOG", "PTH", "Q"]
